### PR TITLE
removing not use attr on class ul li form

### PR DESCRIPTION
**Pull request by abas**
this attr destroy the struct of style form

### CODE REVIEW

**Comment by abas** [comment]
i try my best :smile: 
formfix

**Comment by pvgupta24** [comment]
@ahmadbasir , Can you attach a screenshot of the fixed UI ?

**Comment by abas** [comment]
wait

**Comment by abas** [comment]
that its

**Comment by pvgupta24** [comment]
Good work @ahmadbasir . :+1:

**Comment by abas** [comment]
thanks my brother :+1:

**Pull request merged**
